@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MGIwNmNhMC1kYzkwLTQ3NTMtYmEyOC02YWVkZTc1ZWExMWEiLCJpYXQiOjE3MTAyODUwNTQsImV4cCI6MTcxMDI4ODY1NH0.cELnpzJv1J45bpzT72pZJDlmVF4rJo0VEmjt5D9hBpU

### Login User

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "test@asda.com",
    "password": "123456"
}

### Get Users

GET http://localhost:3000/api/user
Content-Type: application/json
Authorization: Bearer Bearer {{token}}

### Create User

POST http://localhost:3000/api/user
Content-Type: application/json

{
    "name": "teste",
    "email": "test@asda.com",
    "password": "123456"
}

### Login User

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "test@asda.com",
    "password": "123456"
}

### Create Task

POST http://localhost:3000/api/task/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userId": "80b06ca0-dc90-4753-ba28-6aede75ea11a",
    "title": "Minha nova task",
    "description": "Descrição da task",
    "status": "pending"
}

### Create SubTask

POST http://localhost:3000/api/task/96d0e111-15a2-4d98-9cc7-2ba58e552f85/subtasks
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userId": "34e37838-09d8-4d6d-98e8-7cd2ea6e1d0e",
    "title": "Minha nova task",
    "description": "Descrição da task",
    "status": "pending"
}

### Get Task By User ID

GET http://localhost:3000/api/task/80b06ca0-dc90-4753-ba28-6aede75ea11a?status=pending
Content-Type: application/json
Authorization: Bearer {{token}}

### Put Task By User ID

PUT http://localhost:3000/api/task/57ba8875-17ee-449a-be78-2b3192f8f65b
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "completed"
}

### Delete Task By ID

DELETE  http://localhost:3000/api/task/57ba8875-17ee-449a-be78-2b3192f8f65b
Content-Type: application/json
Authorization: Bearer {{token}}
