### Get Users

GET http://localhost:3000/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMjk4NjExMC00NzZlLTRhZjMtYTEyMi1lNjUxM2Y4MDU5MzYiLCJpYXQiOjE3MDk5MDM1MDEsImV4cCI6MTcwOTkwNzEwMX0.4fAf2-vIxZ5AqPH3CGxlP3LkBx3ntYEhg6PzCWL1WpI

### Create User

POST http://localhost:3000/api/user
Content-Type: application/json

{
    "name": "teste",
    "email": "test@asda.com",
    "password": "123456"
}

### Login User

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "test@asda.com",
    "password": "123456"
}

### Create Task

POST http://localhost:3000/api/task
Content-Type: application/json
Authorization: Bearer <seu_token_jwt>

{
    "userId": "e2986110-476e-4af3-a122-e6513f805936",
    "title": "Minha nova task",
    "description": "Descrição da task",
    "status": "pending"
}

### Create Task

POST http://localhost:3000/api/task/12036ccc-bda9-469d-a0f7-d41ee4b02131/subtasks
Content-Type: application/json
Authorization: Bearer <seu_token_jwt>

{
    "userId": "34e37838-09d8-4d6d-98e8-7cd2ea6e1d0e",
    "title": "Minha nova task",
    "description": "Descrição da task",
    "status": "pending"
}

### Get Task By ID

GET http://localhost:3000/api/task/12036ccc-bda9-469d-a0f7-d41ee4b02131
Content-Type: application/json
Authorization: Bearer <seu_token_jwt>
